# service description
services:

  # cloudflare tunnel
  cloudflare-tunnel:
    image: cloudflare/cloudflared
    #build:
    #  context: ./src
    #  dockerfile: ./Dockerfile
    container_name: cloudflared-ferry
    hostname: cloudflare-tunnel
    restart: unless-stopped
    networks:
      ferry:
        ipv4_address: 172.10.0.2
    command: tunnel run
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/hosts:/etc/hosts
    environment:
      - "TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}"
    labels:
      # enbale watchtower updates
      - "com.centurylinklabs.watchtower.enable=true"
  nginx:
    image: nginx
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    networks:
      ferry:
        ipv4_address: 172.10.0.10
        aliases:
          - nginx
    links:
      - code-server:code-server
    depends_on:
      - code-server
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/nginx:/usr/share/nginx/html
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    environment:
      - DOCKER_USER=coder
      - CODE_SERVER_CONFIG=/etc/code-server/config.yaml
    volumes:
      - ./config/vs-code/config.yaml:/etc/code-server/config.yaml
      - $PWD:/home/coder/workspace
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      ferry:
        ipv4_address: 172.10.0.4
        aliases:
          - code-server

networks:
  ferry:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/16
          gateway: 172.10.0.1
